# -*- coding: mbcs -*-
#
# Abaqus/Viewer Release 6.13-1 replay file
# Internal Version: 2013_05_15-22.28.56 126354
# Run by Mike on Sun Feb 28 21:39:43 2016
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
#: Abaqus Error: 
#: This error may have occurred due to a change to the Abaqus Scripting
#: Interface. Please see the Abaqus Scripting Manual for the details of
#: these changes. Also see the "Example environment files" section of 
#: the Abaqus Site Guide for up-to-date examples of common tasks in the
#: environment file.
#: Execution of "onCaeGraphicsStartup()" in the site directory failed.
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=151.785507202148, 
    height=115.546875)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from viewerModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
o1 = session.openOdb(
    name='C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       5
#: Number of Node Sets:          5
#: Number of Steps:              2
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.animationController.stop()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(COMPONENT, 
    'S22'), )
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.showLastFrame()
session.animationController.showLastFrame()
session.animationController.showLastFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=32.6526, 
    farPlane=47.3474, width=0.965984, height=0.760741, viewOffsetX=-1.86949, 
    viewOffsetY=3.72676)
session.animationController.setValues(animationType=NONE)
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.animationController.setValues(animationType=NONE)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=8 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=9 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=10 )
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=11 )
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.animationController.stop()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.showFirstFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
o1 = session.openOdb(
    name='C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       2
#: Number of Node Sets:          2
#: Number of Steps:              2
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].view.setValues(nearPlane=31.8934, 
    farPlane=48.1066, width=3.54995, height=2.79569, viewOffsetX=-2.64366, 
    viewOffsetY=2.60278)
session.viewports['Viewport: 1'].view.setValues(nearPlane=31.9517, 
    farPlane=48.0483, width=3.55644, height=2.8008, viewOffsetX=-2.56147, 
    viewOffsetY=3.34551)
session.viewports['Viewport: 1'].view.setValues(nearPlane=32.7632, 
    farPlane=47.2368, width=0.573289, height=0.451482, viewOffsetX=-3.1285, 
    viewOffsetY=3.92033)
session.animationController.stop()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.showFirstFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=32.9241, 
    farPlane=47.0759, width=0.0171582, height=0.0135126, viewOffsetX=-3.3539, 
    viewOffsetY=4.11041)
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(COMPONENT, 
    'S11'), )
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
o1 = session.openOdb(
    name='C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       2
#: Number of Node Sets:          2
#: Number of Steps:              2
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
#: Warning: The output database 'C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb' disk file has changed.
#: 
#: The current plot operation has been canceled, re-open the file to view the results
o1 = session.openOdb(
    name='C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       5
#: Number of Node Sets:          5
#: Number of Steps:              2
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
#: Warning: The output database 'C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb' disk file has changed.
#: 
#: The current plot operation has been canceled, re-open the file to view the results
session.viewports['Viewport: 1'].view.setValues(nearPlane=32.7385, 
    farPlane=47.2615, width=0.686438, height=0.54059, viewOffsetX=-2.59786, 
    viewOffsetY=3.83886)
o1 = session.openOdb(
    name='C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       5
#: Number of Node Sets:          5
#: Number of Steps:              2
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].view.setValues(nearPlane=32.9017, 
    farPlane=47.0983, width=0.097057, height=0.0764352, viewOffsetX=-3.60501, 
    viewOffsetY=4.0836)
session.animationController.stop()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.showFirstFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(COMPONENT, 
    'S22'), )
session.animationController.decrementFrame()
session.animationController.showFirstFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.showLastFrame()
session.animationController.showLastFrame()
session.animationController.showLastFrame()
session.animationController.showLastFrame()
o1 = session.openOdb(
    name='C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       5
#: Number of Node Sets:          5
#: Number of Steps:              2
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].view.setValues(nearPlane=13837.9, 
    farPlane=25484.5, width=35.302, height=27.8014, viewOffsetX=408.6, 
    viewOffsetY=4.44789)
session.animationController.stop()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.showLastFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=13845.1, 
    farPlane=25477.2, width=10.2099, height=8.04059, viewOffsetX=405.614, 
    viewOffsetY=0.205027)
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=11154.1, 
    farPlane=28168.2, width=895.164, height=704.968, viewOffsetX=348.683, 
    viewOffsetY=-38.9696)
session.animationController.decrementFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=11167.1, 
    farPlane=28155.2, width=896.209, height=705.791, viewOffsetX=-237.174, 
    viewOffsetY=-24.3722)
session.viewports['Viewport: 1'].view.setValues(nearPlane=11167.2, 
    farPlane=28155.2, width=896.213, height=705.794, viewOffsetX=-702.095, 
    viewOffsetY=50.3072)
session.animationController.decrementFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=11167.2, 
    farPlane=28155.2, width=896.209, height=705.791, viewOffsetX=-1741.58, 
    viewOffsetY=-6.8006)
session.viewports['Viewport: 1'].view.setValues(nearPlane=11167.2, 
    farPlane=28155.2, width=896.205, height=705.788, viewOffsetX=-1566.13, 
    viewOffsetY=37.1281)
session.animationController.decrementFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=11167.2, 
    width=896.201, height=705.785, viewOffsetX=-1814.66, viewOffsetY=38.5922)
session.viewports['Viewport: 1'].view.setValues(nearPlane=11362.4, 
    farPlane=27959.9, width=174.48, height=137.408, viewOffsetX=-1870.48, 
    viewOffsetY=9.95624)
session.viewports['Viewport: 1'].view.setValues(nearPlane=11365.5, 
    farPlane=27956.9, width=174.527, height=137.445, viewOffsetX=-1897.74, 
    viewOffsetY=2.83003)
session.viewports['Viewport: 1'].view.setValues(nearPlane=11341.5, 
    farPlane=27980.8, width=248.441, height=195.654, viewOffsetX=-1896.22, 
    viewOffsetY=8.64969)
session.animationController.showFirstFrame()
session.viewports['Viewport: 1'].view.setValues(nearPlane=11401.9, 
    farPlane=27920.5, width=39.8995, height=31.422, viewOffsetX=-1994.88, 
    viewOffsetY=-2.38394)
session.viewports['Viewport: 1'].view.setValues(nearPlane=11402.4, 
    farPlane=27919.9, width=39.9015, height=31.4236, viewOffsetX=-2015.15, 
    viewOffsetY=0.875653)
session.viewports['Viewport: 1'].view.setValues(nearPlane=11410, 
    farPlane=27912.3, width=12.0304, height=9.47428, viewOffsetX=-2014.61, 
    viewOffsetY=0.280238)
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
o1 = session.openOdb(
    name='C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o1)
#: Model: C:/Users/Mike/Documents/GitHub/Up-Frac/ostrich/model0/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       5
#: Number of Node Sets:          5
#: Number of Steps:              2
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='LE', outputPosition=INTEGRATION_POINT, refinement=(
    INVARIANT, 'Max. In-Plane Principal'), )
session.animationController.stop()
session.animationController.decrementFrame()
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='LE', outputPosition=INTEGRATION_POINT, refinement=(
    COMPONENT, 'LE22'), )
session.animationController.showFirstFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.setValues(animationType=NONE)
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].view.setValues(nearPlane=32.8875, 
    farPlane=47.1125, width=0.143347, height=0.11289, viewOffsetX=-3.2678, 
    viewOffsetY=4.06375)
session.animationController.stop()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.showFirstFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(INVARIANT, 
    'Mises'), )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='Extrap. LE', outputPosition=ELEMENT_CENTROID, refinement=(
    INVARIANT, 'Max. In-Plane Principal'), )
session.animationController.setValues(animationType=NONE)
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='PE', outputPosition=INTEGRATION_POINT, refinement=(
    INVARIANT, 'Max. In-Plane Principal'), )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='PEEQ', outputPosition=INTEGRATION_POINT, )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(INVARIANT, 
    'Mises'), )
session.animationController.stop()
session.animationController.decrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(COMPONENT, 
    'S11'), )
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.decrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.setValues(animationType=NONE)
session.animationController.setValues(animationType=TIME_HISTORY, viewports=(
    'Viewport: 1', ))
session.animationController.play(duration=UNLIMITED)
session.animationController.stop()
session.animationController.showFirstFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.animationController.incrementFrame()
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(COMPONENT, 
    'S22'), )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(INVARIANT, 
    'Pressure'), )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(INVARIANT, 
    'Mises'), )
session.viewports['Viewport: 1'].view.setValues(nearPlane=29.8056, 
    farPlane=50.1944, width=11.3253, height=8.91897, viewOffsetX=0.514388, 
    viewOffsetY=-0.279603)
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='LE', outputPosition=INTEGRATION_POINT, refinement=(
    INVARIANT, 'Max. In-Plane Principal'), )
session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(
    variableLabel='PEEQ', outputPosition=INTEGRATION_POINT, )
