function DS = loadData(fileName)
%fileName = 'Vor-Perm-Test-py___t= 0.0000e+000.dat'
    fprintf('Loading %s... ', fileName);    
    
    rawData = importdata(fullfile('data', fileName), ' ')
    rawData.data
    DS = array2table(rawData.data, 'VariableNames', rawData.colheaders);
    
    DS.Properties.UserData.fileName.full = fileName;
    DS.Properties.UserData.fileName.short = fileName(1:strfind(...
        fileName, '___')-1);
    
    calcDS = table(averagePP, dLength, xCoord, yCoord, xNCosine,...
        yNCosine,'VariableNames',...
        {'averagePP', 'dLength', 'xCoord', 'yCoord', 'xNCosine',...
        'yNCosine'});
    
    DS = [DS, calcDS];
    
    DSMissing = ismissing(DS);
    DS = DS(~any(DSMissing,2),:);
    
    fprintf('Done\n\n')
end

%         function calculateConnectivity(self)
%             self.connectivity.nodes = unique([[self.x1,...
%                 self.y1];[self.x2,...
%                 self.y2]], 'rows');
%             self.connectivity.nodes = [...
%                 (1:length(self.connectivity.nodes))',...
%                 self.connectivity.nodes];
%             
%             self.connectivity.contacts = zeros(...
%                 [length(self.x1), 3]);
%             for i  = 1:length(self.x1)
%                 i1 = find(self.x1(i) ==...
%                     self.connectivity.nodes(:, 2) &...
%                     self.y1(i) ==...
%                     self.connectivity.nodes(:, 3));
%                 i2 = find(self.x2(i) ==...
%                     self.connectivity.nodes(:, 2) &...
%                     self.y2(i) ==...
%                     self.connectivity.nodes(:, 3));
%                 self.connectivity.contacts(i, :) = [i, i1, i2];
%             end              
%         end
%     end
